jdi-testing/jdi-light-csharp

JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/UIObjects/Pages/HomePage.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/Header.cs
JDI.Light/JDI.Light.Tests/UITests/Composite/MenuTests.cs
JDI.Light/JDI.Light/Elements/Base/Clickable.cs
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Elements/Composite/Menu.cs
JDI.Light/JDI.Light/Elements/Composite/NavigationPane.cs
JDI.Light/JDI.Light/Elements/Composite/Pagination.cs
JDI.Light/JDI.Light/Exceptions/ElementNotFoundException.cs
JDI.Light/JDI.Light/Extensions/TimerExtensions.cs
JDI.Light/JDI.Light/Interfaces/Base/IBaseUIElement.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Added mune UI element covered with tests

Menu added

---

JDI.Light/JDI.Light.Tests/UITests/TestBase.cs
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Utils/WebDriverByUtils.cs

Change log:
- Adds refresh for speeding up tests;
- Removed useless method.

Small fixes

---

JDI.Light/JDI.Light.Tests/Entities/Client.cs
JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Composite/FormTests.cs
JDI.Light/JDI.Light.Tests/Tests/Composite/WebPageTests.cs
JDI.Light/JDI.Light.Tests/Tests/TestBase.cs
JDI.Light/JDI.Light.Tests/UIObjects/Forms/LoginFormClient.cs
JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs
JDI.Light/JDI.Light/Elements/Composite/Form.cs
JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Elements/Composite/WebSite.cs
JDI.Light/JDI.Light/Extensions/ObjectExtensions.cs
JDI.Light/JDI.Light/Factories/WebPageFactory.cs
JDI.Light/JDI.Light/Interfaces/Base/IGetValue.cs
JDI.Light/JDI.Light/Interfaces/Composite/IForm.cs
JDI.Light/JDI.Light/Utils/ReflectionUtils.cs

add static pages, add as form, fix forms for private, add PageUrl and PageTitle as static

add static pages, add as form, fix forms for private, add PageUrl and PageTitle as static

---

JDI.Light/JDI.Light.Tests/Tests/Common/ButtonTests.cs
JDI.Light/JDI.Light.Tests/Tests/TestBase.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/MetalsColorsPage.cs
JDI.Light/JDI.Light/Attributes/ByText.cs
JDI.Light/JDI.Light/Attributes/CssAttribute.cs
JDI.Light/JDI.Light/Attributes/XPathAttribute.cs
JDI.Light/JDI.Light/Extensions/MemberInfoExtensions.cs
JDI.Light/JDI.Light/JDI.Light.csproj

add css and xpath locator attributes

add css and xpath locator attributes

---

JDI.Light/JDI.Light.Tests/Tests/Common/ButtonTests.cs
JDI.Light/JDI.Light.Tests/Tests/TestBase.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/MetalsColorsPage.cs
JDI.Light/JDI.Light/Attributes/ByText.cs
JDI.Light/JDI.Light/Attributes/CssAttribute.cs
JDI.Light/JDI.Light/Attributes/XPathAttribute.cs
JDI.Light/JDI.Light/Extensions/MemberInfoExtensions.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Properties/AssemblyInfo.cs

Add new Attributes: Css, XPath, ByText
Add capability to use Static page objects
Correct Form entities usage

Release 0.2.0.4

---

JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Composite/AlertTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/BasePage.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/DatesPage.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/MetalsColorsPage.cs
JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs
JDI.Light/JDI.Light/Elements/Composite/Alert.cs
JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Utils/ReflectionUtils.cs

1. Created new class Alert.cs with methods implemented work with alerts
2. Created new class AlertTests.cs with one test covering all alert actions
3. Created new class Html5Page.cs

Added Alert class with alerts action methods and AlertTests class

---

JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Common/FileInputTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs
JDI.Light/JDI.Light/Elements/Composite/FileInput.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Added Html5 page into examples project
Added test for FileInput component
closes #47

Added FileInput component

---

JDI.Light/JDI.Light.Tests/Enums/Colors.cs
JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Common/RadioButtonTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Elements/Common/RadioButton.cs
JDI.Light/JDI.Light/Interfaces/Common/IRadioButton.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Created IRadioButton interface 
Implemented it in RadioButton class
Wrote tests for this functional

RadioButton

---

JDI.Light/JDI.Light/Interfaces/Common/IIcon.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Settings/MapInterfaceToElement.cs

created IIcon interface
`closes #142 `

added IIcon interface

---

JDI.Light/JDI.Light.Tests/Tests/Simple/ImagesTests.cs
JDI.Light/JDI.Light/Elements/Common/Image.cs
JDI.Light/JDI.Light/Interfaces/Common/IImage.cs

image interface synchronized according to java

image synchronized with java

---

JDI.Light/JDI.Light.Tests/Tests/Simple/RangeTests.cs
JDI.Light/JDI.Light/Asserts/RangeAssert.cs
JDI.Light/JDI.Light/Elements/Common/Range.cs
JDI.Light/JDI.Light/Interfaces/Common/IRange.cs
JDI.Light/JDI.Light/JDI.Light.csproj

RangeAsserts implemented

---

JDI.Light/JDI.Light.Tests/Tests/Simple/LinkTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Asserts/LinkAssert.cs
JDI.Light/JDI.Light/Elements/Common/Link.cs
JDI.Light/JDI.Light/Interfaces/Common/ILink.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Matchers/Is.cs
JDI.Light/JDI.Light/Matchers/StringMatchers/EqualToIgnoringCaseMatcher.cs

LinkAsserts implemented

---

JDI.Light/JDI.Light.Tests/Tests/Common/TextFieldsTests.cs
JDI.Light/JDI.Light.Tests/Tests/Common/UIElementTests.cs
JDI.Light/JDI.Light.Tests/Tests/Simple/ColorPickerTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/MetalsColorsPage.cs
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Elements/Common/ColorPicker.cs
JDI.Light/JDI.Light/Elements/Complex/Generic/CheckList.cs
JDI.Light/JDI.Light/Elements/Composite/Form.cs
JDI.Light/JDI.Light/Elements/Composite/MultiDropdownElement.cs
JDI.Light/JDI.Light/Interfaces/Base/HasLabel.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Added element's label support.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/ImagesTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Asserts/ImageAssert.cs
JDI.Light/JDI.Light/Elements/Common/Image.cs
JDI.Light/JDI.Light/Interfaces/Common/IImage.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Image asserts implemented

---

JDI.Light/JDI.Light.Tests/Tests/Simple/TextTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/HomePage.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Elements/Base/BaseValidation.cs
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Elements/Common/TextElement.cs
JDI.Light/JDI.Light/Elements/Composite/Menu.cs
JDI.Light/JDI.Light/Interfaces/Base/IBaseUIElement.cs
JDI.Light/JDI.Light/Interfaces/Common/ITextElement.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Added Assert methods for Text Element

---

JDI.Light/JDI.Light.Tests/Tests/Composite/MenuTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Asserts/MenuSelectAssert.cs
JDI.Light/JDI.Light/Elements/Complex/CheckList.cs
JDI.Light/JDI.Light/Elements/Composite/Menu.cs
JDI.Light/JDI.Light/Interfaces/Asserts/IHasSelectMenuAssert.cs
JDI.Light/JDI.Light/Interfaces/Complex/Generic/ICheckList.cs
JDI.Light/JDI.Light/Interfaces/Complex/IMenuSelector.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Settings/MapInterfaceToElement.cs

Implemented asserts for Menu.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/ColorPickerTests.cs
JDI.Light/JDI.Light/Asserts/ColorAssert.cs
JDI.Light/JDI.Light/Elements/Common/ColorPicker.cs
JDI.Light/JDI.Light/Interfaces/Common/IColorPicker.cs
JDI.Light/JDI.Light/JDI.Light.csproj

ColorPickerAsserts implemented

---

JDI.Light/JDI.Light.Tests/Tests/Simple/TextTests.cs
JDI.Light/JDI.Light/Elements/Common/TextElement.cs
JDI.Light/JDI.Light/Interfaces/Common/ITextElement.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Matchers/StringMatchers/RegexMatcher.cs

Removed wait tests from TextTests.cs

---

JDI.Light/JDI.Light.Tests/Tests/Common/DataListTests.cs
JDI.Light/JDI.Light/Asserts/DataListAssert.cs
JDI.Light/JDI.Light/Elements/Common/DataList.cs
JDI.Light/JDI.Light/Elements/Common/TextElement.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Added Data List asserts.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/FileInputTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs

Added some file Input tests.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/ButtonTests.cs

added assert tests

---

JDI.Light/JDI.Light.Tests/Tests/Common/DataListTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Elements/Common/DataList.cs

Implemented some negative cases for DataList

---

JDI.Light/JDI.Light.Tests/Tests/Common/DropDownTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Asserts/DropDownAssert.cs
JDI.Light/JDI.Light/Elements/Common/DropDown.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Added asserts for DropDown.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/CheckBoxTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Asserts/CheckboxAssert.cs
JDI.Light/JDI.Light/Elements/Common/CheckBox.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Implemented asserts for checkbox

---

JDI.Light/JDI.Light.Tests/Tests/Common/ComboBoxTests.cs
JDI.Light/JDI.Light/Asserts/ComboBoxAssert.cs
JDI.Light/JDI.Light/Elements/Common/ComboBox.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Added CmbBox Assert

---

JDI.Light/JDI.Light.Tests/Tests/Simple/TitleTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Asserts/TitleAssert.cs
JDI.Light/JDI.Light/Elements/Common/Title.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Matchers/StringMatchers/IsMatcher.cs

Implemented Asserts for Title element.

---

JDI.Light/JDI.Light.Tests/Tests/Complex/RadioButtonsTests.cs
JDI.Light/JDI.Light/Asserts/RadioButtonAssert.cs
JDI.Light/JDI.Light/Elements/Complex/RadioButtons.cs
JDI.Light/JDI.Light/Interfaces/Complex/IRadioButtons.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Radio assert added

---

JDI.Light/JDI.Light.Tests/Tests/Composite/TableTests.cs

Changed few tests for TableAssert

---

JDI.Light/JDI.Light.Tests/Tests/Composite/MultiDropdownTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/ContactPage.cs
JDI.Light/JDI.Light/Asserts/MultiDropdownAssert.cs
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Elements/Composite/MultiDropdown.cs
JDI.Light/JDI.Light/Elements/Composite/MultiDropdownElement.cs
JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Elements/WebActions/ActionInvoker.cs
JDI.Light/JDI.Light/Interfaces/Base/HasLabel.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Implemented asserts for MultiDropDown.

---

JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Composite/CustomSectionTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/ContactPage.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/MetalsColorsPage.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/Contact.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/Footer.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/Header.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/JdiSearch.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/Summary.cs
JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs
JDI.Light/JDI.Light/Asserts/SelectAssert.cs
JDI.Light/JDI.Light/Elements/Common/MultiSelector.cs
JDI.Light/JDI.Light/Elements/Complex/Generic/CheckList.cs
JDI.Light/JDI.Light/Elements/Composite/Section.cs
JDI.Light/JDI.Light/Extensions/UIElementExtensions.cs
JDI.Light/JDI.Light/Interfaces/Complex/IHasSize.cs

Implemented some tests for Custom Section.

---

JDI.Light/JDI.Light/Asserts/TableAssert.cs
JDI.Light/JDI.Light/Elements/Complex/Table/Table.cs

Replaced Size and IsTableEmpty methods from TableAssert to Table class.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/ButtonTests.cs
JDI.Light/JDI.Light/Elements/Base/BaseValidation.cs

Finished implementing BaseValidation class.

---

JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Composite/MenuTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/UsersTablePage.cs
JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs
JDI.Light/JDI.Light/Asserts/MenuSelectAssert.cs
JDI.Light/JDI.Light/Elements/Composite/Menu.cs
JDI.Light/JDI.Light/Extensions/EnumExtensions.cs
JDI.Light/JDI.Light/Interfaces/Complex/IMenuSelector.cs

Synchronized Menu methods with java version.

---

JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Composite/PseudoSiteTests/AnnotationsWebPageTests.cs
JDI.Light/JDI.Light.Tests/Tests/Composite/PseudoSiteTests/CustomSectionTests.cs
JDI.Light/JDI.Light.Tests/Tests/Composite/PseudoSiteTests/CustomSectionUITests.cs
JDI.Light/JDI.Light.Tests/Tests/Composite/PseudoSiteTests/ExtendedSectionTests.cs
JDI.Light/JDI.Light.Tests/Tests/Composite/PseudoSiteTests/ExtendedSectionUITests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/PseudoSite/PageWithBoth.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/PseudoSite/PageWithTitle.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/PseudoSite/PageWithUrl.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/PseudoSite/PageWithoutBoth.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/PseudoSite/PseudoSitePage.cs
JDI.Light/JDI.Light.Tests/UIObjects/PseudoSections/CustomSection.cs
JDI.Light/JDI.Light.Tests/UIObjects/PseudoSections/ExtendedSection.cs
JDI.Light/JDI.Light.Tests/UIObjects/PseudoSite/PseudoSitePage.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/PseudoSections/CustomSection.cs
JDI.Light/JDI.Light.Tests/UIObjects/Sections/PseudoSections/ExtendedSection.cs
JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs

Partially implemented tests for Pseudo Site's section.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/IconTests.cs
JDI.Light/JDI.Light.Tests/Tests/Simple/ImagesTests.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/Html5Page.cs
JDI.Light/JDI.Light/Elements/Common/Icon.cs

Added some base validation tests to Icon and Image.

---

JDI.Light/JDI.Light/Elements/Base/JDIBase.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Settings/WebSettings.cs
JDI.Light/JDI.Light/Tools/CacheValue.cs

Implemented validation rules

---

JDI.Light/JDI.Light/Elements/Init/EntitiesCollection.cs
JDI.Light/JDI.Light/Elements/WebCascadeInit.cs
JDI.Light/JDI.Light/JDI.Light.csproj

Implemented filling of Pages and Elements collections for BDD-steps.

---

JDI.Light/JDI.Light.Tests/Tests/Common/DatePickerTests.cs
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Elements/Common/CheckBox.cs
JDI.Light/JDI.Light/Elements/Common/Selector.cs
JDI.Light/JDI.Light/Elements/Composite/Form.cs
JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Elements/WebActions/ActionInvoker.cs
JDI.Light/JDI.Light/Extensions/StringExtensions.cs
JDI.Light/JDI.Light/Factories/WebDriverFactory.cs
JDI.Light/JDI.Light/Utils/WebDriverUtils.cs

Fixed codacy issues for curly braces.

---

JDI.Light/JDI.Light.Tests/Tests/Simple/FileInputTests.cs

Fixed test for FileInput.

---

JDI.Light/JDI.Light/Elements/Init/EntitiesCollection.cs

Methods to get WebElements from Entities Collection.
#324

Methods to get WebElements from Entities Collection for #324

---

JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/Tests/Composite/SiteDomainTests.cs
JDI.Light/JDI.Light.Tests/Tests/Simple/CheckBoxTests.cs
JDI.Light/JDI.Light.Tests/packages.config
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Elements/Common/TextElement.cs
JDI.Light/JDI.Light/Elements/Composite/Form.cs
JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Elements/WebActions/ActionInvoker.cs
JDI.Light/JDI.Light/Extensions/MemberInfoExtensions.cs
JDI.Light/JDI.Light/Factories/WebDriverFactory.cs
JDI.Light/JDI.Light/Factories/WebPageFactory.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Utils/BaseAsserter.cs
JDI.Light/JDI.Light/Utils/ReflectionUtils.cs
JDI.Light/JDI.Light/Utils/StaTaskScheduler.cs
JDI.Light/JDI.Light/packages.config

Task:https://github.com/jdi-testing/jdi-light-csharp/issues/285
Coadcy Pattern: Add curly braces around the nested statement(s) in this 'if' block.
**NOTE:** 
**by mistake changes in file
JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
also getting in current commit**
Sorry.
-------------------------------------✄ cut line ----------------------------------------------
Demonstrate the code …

Task285-Add_curly_braces

---

JDI.Light/JDI.Light/JDI.Light.csproj

Fixed JDI.Light.csproj file.

---

JDI.Light/JDI.Light/Factories/WebDriverFactory.cs

Fixed curly braces for GetDriver method.

---

JDI.Light/JDI.Light.Tests/Tests/Composite/SiteDomainTests.cs
JDI.Light/JDI.Light.Tests/Tests/TestBase.cs
JDI.Light/JDI.Light.Tests/UIObjects/Forms/LoginForm.cs
JDI.Light/JDI.Light/Elements/Base/UIElement.cs
JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Elements/Init/EntitiesCollection.cs

#324 `Create a class with utils for casting elements from elements' collection (Object type) to some definite type. Look at EntitiesCollection class in java.`
Implemented methods to GetPage and GetWebElement minding current page.

Implement methods GetPage and GetWebElement minding current page

---

JDI.Light/JDI.Light/Elements/Init/EntitiesCollection.cs
JDI.Light/JDI.Light/Elements/WebCascadeInit.cs

#342 Added `if` clause for Pages entity.

Fix multiple test run issue

---

JDI.Light/JDI.Light/Elements/Complex/Table/NameNum.cs
JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Factories/UIElementFactory.cs

Codacy Pattern: 
Members should not be initialized to default values
https://app.codacy.com/manual/jdi-testing/jdi-light-csharp/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJJbmZvIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjQ0MDAiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==
Explain the **details** for making this change. What existing …

Task318 Remove Default Values

---

JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Extensions/ObjectExtensions.cs
JDI.Light/JDI.Light/Factories/WebDriverFactory.cs
JDI.Light/JDI.Light/Utils/WebDriverUtils.cs

ad default case to switch statement

---

JDI.Light/JDI.Light/Elements/Complex/Generic/CheckList.cs
JDI.Light/JDI.Light/Elements/Complex/RadioButtons.cs

7/11/2020 Alex T:rename 2 methods add prefix Is, to make difference between parameter and method names
Put `closes …

rename 2 methods add prefix Is, yo make difference between parameter and methos names

---

JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Utils/WebDriverUtils.cs

update switch statement in 2 files regarding new codacy report

---

JDI.Light/JDI.Light/Elements/Composite/WebPage.cs
JDI.Light/JDI.Light/Factories/WebDriverFactory.cs

update WebDriverFactory replace switch 2 cases statement to if else

---

JDI.Light/JDI.Light.Tests/Utils/FileLogger.cs

Alex T:07/14/2020:
Task359_changeAccessLevel
Codacy Pattern:
https://app.codacy.com/manual/jdi-testing/jdi-light-csharp/issues?bid=10276502&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjQyOTAiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ
==
Explain the **details** for making this change. What existing …

change constant Access Level

---

JDI.Light/JDI.Light.Tests/Entities/Client.cs
JDI.Light/JDI.Light.Tests/Entities/User.cs
JDI.Light/JDI.Light.Tests/Tests/TestBase.cs
JDI.Light/JDI.Light.Tests/UIObjects/Pages/BasePage.cs
JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs
JDI.Light/JDI.Light/Elements/Composite/Form.cs
JDI.Light/JDI.Light/JDI.cs

Tasks336 fix fiedls accessibility

---

JDI.Light/JDI.Light.Tests/UIObjects/TestSite.cs

update access level from LoginFormPage variable in TestSite.cs

---

JDI.Light/JDI.Light.Tests/UIObjects/Forms/ContactForm.cs

7/27/2020
Alex T:
update Contact Form class modify access level from public to private for 2 fields:"FirstRolle"r and "SecondRoller" 
**Reason**: it used only in class where declared
… only in class where declared
Demonstrate the code is solid. Example: The exact commands you ran and their …

update Contact Form class modify access level from public to private for 2 fields:"FirstRoller" and "SecondRoller"

---

JDI.Light/JDI.Light/Settings/Timeouts.cs

Task256  codacy category error phone

---

.gitignore
JDI.Light/JDI.Light/Settings/Timeouts.cs

9/28/2020: Aleksander_Tsvetaev@epam.com
update Timeouts modify fields protection level
update Timeouts modify fields protection level
update gitignore sdd GIT-specific folder
sdd GIT-specific folder to git ignore
.git/
Demonstrate the code is solid. Example: The exact commands you ran and their …

Fix codacy warnings

---

.gitignore

9/28/2020: Aleksander_Tsvetaev@epam.com
add GIT-specific folder and subfolders
.git/*

GIT-specific folder and sybfolders

---

.github/workflows/dotnetcore.yml
.gitignore
JDI.Light/JDI.Light.Tests/Entities/Client.cs
JDI.Light/JDI.Light.Tests/JDI.Light.Tests.csproj
JDI.Light/JDI.Light.Tests/packages.config
JDI.Light/JDI.Light/Factories/WebDriverFactory.cs
JDI.Light/JDI.Light/JDI.Light.csproj
JDI.Light/JDI.Light/Utils/BaseAsserter.cs

Add vscode ignore
